<?php
    $hopitalManager = new hopitalManager(connexion("bdd_hms"));
    $result = $hopitalManager->getAllHopital();
?>

<div class="topnav">
    <a class="active" style="float:right" href="dashboard/projet/mvc/connection">Se connecter</a>
    <a class="active" style="float:right" href="dashboard/projet/mvc/inscription">Inscription</a>
    <a class="active" style="float:right" href="dashboard/projet/mvc/accueil">Accueil</a>
</div> 

<div class="items">
    <div class=tSante><h2><?php echo $result[0]->getNom();?></h2></div>
    <div class=tCoeur><h2><?php echo $result[1]->getNom();?></h2></div>
    <div class=tRosemont><h2><?php echo $result[2]->getNom();?></h2></div>
    <div class=tTalon><h2><?php echo $result[3]->getNom();?></h2></div>
</div>

<div class="items">
    <span class="imgSante">
        <?php
            $contenu0 ="<a href=dashboard/projet/mvc/infoHopital?idHopital='".$result[0]->getIdHopital()."'>";
            $contenu0 .="<img style=width:80%;height:500px;margin-left:10% src='".$result[0]->getPhoto()."'; alt=error/></a>";
            echo $contenu0;
        ?>
    </span>
    <span class="imgCoeur">
        <?php
            $contenu1 ="<a href=dashboard/projet/mvc/infoHopital?idHopital='".$result[1]->getIdHopital()."'>";
            $contenu1 .="<img style=width:80%;height:500px;margin-left:10% src='".$result[1]->getPhoto()."'; alt=error/></a>";
            echo $contenu1;
        ?>
    </span>
    <span class="imgRosemont">
        <?php
            $contenu2 ="<a href=dashboard/projet/mvc/infoHopital?idHopital='".$result[2]->getIdHopital()."'>";
            $contenu2 .="<img style=width:80%;height:500px;margin-left:10% src='".$result[2]->getPhoto()."'; alt=error/></a>";
            echo $contenu2;
        ?>
    </span> 
    <span class="imgTalon">
        <?php
            $contenu3 ="<a href=dashboard/projet/mvc/infoHopital?idHopital='".$result[3]->getIdHopital()."'>";
            $contenu3 .="<img style=width:80%;height:500px;margin-left:10% src='".$result[3]->getPhoto()."'; alt=error/></a>";
            echo $contenu3;
        ?>
    </span>
</div>
<br><br>