<style>
.center {  margin: auto;  width: 60%;  border: 3px solid lightskyblue;  padding: 10px;}
.card {  float: left; background: rgba(0, 128, 0, 0.3);box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);  transition: 0.3s;  width: 300px;  border-radius: 5px;  padding: 10px;margin: 10px;}
.card:hover {  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);}
.container {  width:100%;}
</style>
<?php
include_once("./fonction.php");
$debut = 0;

$sexeManager = new sexeManager(connexion("bdd_hms"));
$resultSexe = $sexeManager->getAllSexe();

$sangManager = new groupeSanguinManager(connexion("bdd_hms"));
$resultSang = $sangManager->getAllSang();

if(isset($_POST['transferer'])){
    $employerManager = new employerManager(connexion("bdd_hms"));
    $resultEmployer = $employerManager->getInfirmiere(3);
    if($resultEmployer != null){
        $debut = 1;

        foreach($resultEmployer as $key1 => $value1){
            $sheduleManager = new sheduleManager(connexion("bdd_hms"));
            $resultShedule = $sheduleManager->getSheduleDispo($value1->getIdEmployer());

            $hopitalManager = new hopitalManager(connexion("bdd_hms"));
            $resultHopital = $hopitalManager->getHopital($value1->getIdHopital());
            foreach($resultShedule as $key2 => $value2){
                $contenu2  ="<div class=card>";
                $contenu2 .="<form method='post'><div class=container>";    
                $contenu2 .="        <h3 class=card-title>".$resultHopital->getNom()."</h3><hr>";
                $contenu2 .="        <p class=card-text>Nom : ".$value1->getPrenom()." ".$value1->getNom()."</p>";
                $contenu2 .="        <p class=card-text>No Employer : ".$value1->getIdEmployer()."</p>";
                $contenu2 .="        <p class=card-text>Date : ".$value2->getJour()."</p>";
                $contenu2 .="        <p class=card-text>Shedule : ".$value2->getShedule()."</p>";
                $contenu2 .="        <p class=card-text>Frais : ".$value2->getFrais()."</p>";
                $contenu2 .="        <input type='hidden' name='idShedule' value=".$value2->getIdShedule()." >";
                $contenu2 .="        <input type='hidden' name='Cmp' value=".$value2->getCmpPatient().">";
                $contenu2 .="        <input type='hidden' name='idEmp' value=".$value1->getIdEmployer().">";
                $contenu2 .="        <input type='hidden' name='idHopital' value=".$value1->getIdHopital().">";
                $contenu2 .="        <input type='hidden' name='idPatient' value=".$_POST["idPatient"].">";
                $contenu2 .="        <input type='submit' style=width:100px name='trans' value='Transférer'><br>";
                $contenu2 .="    </div></div></form>";
                echo $contenu2;
            }
        }
    }
}
if(isset($_POST['trans'])){
    $Cmp = $_POST["Cmp"] - 1;
    $arrayDefaultShedule = array("idShedule" => $_POST['idShedule'],"cmpPatient" => $Cmp);
    $sheduleDefault = new shedule($arrayDefaultShedule);
    $sheduleManager = new sheduleManager(connexion("bdd_hms"));
    $sheduleManager->updateCmp($sheduleDefault);

    $array = array("idShedule" => $_POST['idShedule'], "idPatient"=>$_POST["idPatient"],"idEmployer"=>$_POST["idEmp"],"idHopital"=>$_POST["idHopital"]);
    $rendezvous = new rendezvous($array);
    $rendezvousManager = new rendezvousManager(connexion("bdd_hms"));
    $rendezvousManager->insertion($rendezvous);

    if($Cmp == 0){
        $arrayNouvelShedule = array("idShedule" => $_POST['idShedule'],"disponibilite" => $Cmp);
        $sheduleNouvel = new shedule($arrayNouvelShedule);
        $sheduleManager->updateDisponibilite($sheduleNouvel);
    }

    echo "<center><p style=color:green;>Patient Transféré!</p></center>";
}
if($debut == 0){
?>

<center>
<div >
        <h1 style=color:black>Gestion compte patient</h1>
        <table>
            <tr><form method="post">
                <td>Recherche patient  </td>
                <td><input type="text" name="assuranceMaladieTrouver" style="width:42%"; pattern="[A-Z]{4}[0-9]{8}" placeholder="AAAA12345678" maxlength='20' required><input type="submit" name="trouver" value="Trouver"></td>
                </form>
            </tr>
            <tr>
            <form method="post">
            <tr>
                <td>Prénom  </td>
                <td><input type="text" name="prenom" id="prenom" maxlength='30' required></td>
            </tr>
            <tr>
                <td>Nom  </td>
                <td><input type="text" name="nom" id="nom" maxlength='30' required></td>
            </tr>
            <tr>
                <td>Téléphone  </td>
                <td><input type="text" name="telephone" id="telephone" pattern="[0-9]{10}" placeholder="5140000000" required></td>
            </tr>
            <tr>
                <td>Adresse  </td>
                <td><input type="text" name="adresse" id="adresse" maxlength='100' required></td>
            </tr>
            <tr>
                <td>Ville  </td>
                <td><input type="text" name="ville" id="ville" maxlength='50' required></td>
            </tr>
            <tr>
                <td>Code Postal  </td>
                <td><input type="text" name="codePostal" id="codePostal" pattern="[A-Z]{1}[0-9]{1}[A-Z]{1}[0-9]{1}[A-Z]{1}[0-9]{1}" placeholder="X1X1X1" required></td>
            </tr>
            <tr>
                <td>Sexe  </td>
                <td>
                <?php
                $contenu ="<select name=sexe id=sexe style=width:74%;>";
                foreach($resultSexe as $key => $value){
                    $contenu .="<option value=".$value->getIdSexe().">".$value->getGenre()."</option>";
                }
                $contenu .="</select>";
                echo $contenu;
                ?>
            </tr>
            <tr>
                <td>Groupe Sanguin  </td>
                <td>
                <?php
                $contenu1 ="<select name=grpSang  id=grpSang style=width:74%;>";
                foreach($resultSang as $key => $value){
                    $contenu1 .="<option value=".$value->getIdGrpSang().">".$value->getGroupeSanguin()."</option>";
                }
                $contenu1 .="</select>";
                echo $contenu1;
                ?>
                </td>
            </tr>
            <tr>
                <td>Assurance Maladie  </td>
                <td><input type="text" name="assuranceMaladie" id="assuranceMaladie" pattern="[A-Z]{4}[0-9]{8}" placeholder="AAAA12345678" maxlength='20' required></td>
            </tr>
            <tr>
                <td>Description  </td>
                <td><textarea name="description" id="description" maxlength='500' style="width:71%"></textarea></td>
            </tr>
            <tr>
                <td>Pays de naissance  </td>
                <td><input type="text" name="paysNaissance" id="paysNaissance" maxlength='50' required></td>
            </tr>
            <tr>
                <td>Date de naissance  </td>
                <td><input type="date" name="dateNaissance" id="dateNaissance" style="width:71%" required></td>
            </tr>
            <tr>
                <td>Pseudo  </td>
                <td><input type="text" name="pseudo" id="pseudo" minlength="6" maxlength='30' required></td>
            </tr>
            <tr>
                <td>Mot de passe  </td>
                <td><input type="password" name="motDePasse" id="motDePasse" minlength="6" maxlength='30' required></td>
            </tr>
            <tr>
                <td><input type='hidden' name='idPatient' id="idPatient"></td>
                <td><input type="submit" name="inscrire" style="width:37%" value="Inscrire"><input type="submit" style="width:37%" name="modifier" value="Modifier"></td>
            </tr>
        <table>
    </form>

    <?php
        if(isset($_POST['inscrire'])){
            if($_POST["dateNaissance"] > date("Y-m-d")){
                echo '<script>alert("Entrer une date de naissance valide!")</script>';
            }
            else{
                $array = array("prenom" => trim($_POST['prenom']),
                "description" => trim($_POST['description']),
                "nom" => trim($_POST['nom']),
                "telephone" => trim($_POST['telephone']),
                "adresse" => trim($_POST['adresse']),
                "ville" => trim($_POST['ville']),
                "codePostal" => trim($_POST['codePostal']),
                "idSexe" => $_POST['sexe'],
                "idGrpSang" => $_POST['grpSang'],
                "assuranceMaladie" => trim($_POST['assuranceMaladie']),
                "paysNaissance" => trim($_POST['paysNaissance']),
                "dateNaissance" => $_POST['dateNaissance'],
                "pseudo" => trim($_POST['pseudo']),
                "motDePasse" => trim($_POST['motDePasse']));

                $patient = new patient($array);
                $patientManager = new patientManager(connexion("bdd_hms"));
                try{
                $patientManager->gestionPatientInsertion($patient);
                echo "<center><p style=color:green;>Patient inscrit!</p></center>";
                }
                catch(Exception $e){
                    echo '<script>alert("Insertion échoué! Pseudo ou Assurance maladie est déjà utilisé!")</script>';
                }
            }
        }
        if(isset($_POST['trouver'])){
            $array = array("assuranceMaladie" => $_POST['assuranceMaladieTrouver']);
            $patient = new patient($array);
            $patientManager = new patientManager(connexion("bdd_hms"));
            $result = $patientManager->getGestionPatient($patient);

            if($result != null){
                ?>
                <script>document.getElementById("idPatient").value = '<?php  echo $result->getIdPatient(); ?>'</script>
                <script>document.getElementById("prenom").value = '<?php  echo $result->getPrenom(); ?>'</script>
                <script>document.getElementById("nom").value = '<?php  echo $result->getNom(); ?>'</script>
                <script>document.getElementById("telephone").value = '<?php  echo $result->getTelephone(); ?>'</script>
                <script>document.getElementById("adresse").value = '<?php  echo $result->getAdresse(); ?>'</script>
                <script>document.getElementById("ville").value = '<?php  echo $result->getVille(); ?>'</script>
                <script>document.getElementById("codePostal").value = '<?php  echo $result->getCodePostal(); ?>'</script>
                <script>document.getElementById("sexe").value = '<?php  echo $result->getIdSexe(); ?>'</script>
                <script>document.getElementById("grpSang").value = '<?php  echo $result->getIdGrpSang(); ?>'</script>
                <script>document.getElementById("assuranceMaladie").value = '<?php  echo $result->getAssuranceMaladie(); ?>'</script>
                <script>document.getElementById("description").value = '<?php  echo $result->getDescription(); ?>'</script>
                <script>document.getElementById("paysNaissance").value = '<?php  echo $result->getPaysNaissance(); ?>'</script>
                <script>document.getElementById("dateNaissance").value = '<?php  echo $result->getDateNaissance(); ?>'</script>
                <script>document.getElementById("pseudo").value = '<?php  echo $result->getPseudo(); ?>'</script>
                <script>document.getElementById("motDePasse").value = '<?php  echo $result->getMotDePasse(); ?>'</script>
                <?php
            }
            else{
                echo '<script>alert("Se patient a aucun rendez-vous à cette hopital!")</script>';
            }
            
        }
        if(isset($_POST['modifier'])){
            if($_POST["dateNaissance"] > date("Y-m-d")){
                echo '<script>alert("Entrer une date de naissance valide!")</script>';
            }
            else{
                $array = array("prenom" => trim($_POST['prenom']),
                "idPatient" => $_POST["idPatient"],
                "description" => trim($_POST['description']),
                "nom" => trim($_POST['nom']),
                "telephone" => trim($_POST['telephone']),
                "adresse" => trim($_POST['adresse']),
                "ville" => trim($_POST['ville']),
                "codePostal" => trim($_POST['codePostal']),
                "idSexe" => $_POST['sexe'],
                "idGrpSang" => $_POST['grpSang'],
                "assuranceMaladie" => trim($_POST['assuranceMaladie']),
                "paysNaissance" => trim($_POST['paysNaissance']),
                "dateNaissance" => $_POST['dateNaissance'],
                "pseudo" => trim($_POST['pseudo']),
                "motDePasse" => trim($_POST['motDePasse']));

                $patient = new patient($array);
                $patientManager = new patientManager(connexion("bdd_hms"));
                try{
                $patientManager->gestionPatientModifier($patient);
                echo "<center><p style=color:green;>Patient Modifier!</p></center>";
                }
                catch(Exception $e){
                    echo '<script>alert("Erreur Modification!")</script>';
                }
            }
        }
    ?>
</div>
</center>
<br><br><br>
<?php
$employerManager = new employerManager(connexion("bdd_hms"));
$hopitalManager = new hopitalManager(connexion("bdd_hms"));
$prescriptionManager = new prescriptionManager(connexion("bdd_hms"));
$patientManager = new patientManager(connexion("bdd_hms"));
$resultPatient = $patientManager->getAllPatient();

foreach($resultPatient as $key => $value){

    $sang = $sangManager->getSang($value->getIdGrpSang());
    $sexe = $sexeManager->getSexe($value->getIdSexe());
    $contenu2  ="<div class=card>";
    $contenu2 .="<form method='post'><div class=container>";
    $contenu2 .="        <h3 class=card-title>".$value->getPrenom()." ".$value->getNom()."</h3><hr>";
    $contenu2 .="        <p class=card-text style=background-color: green>Telephone : ".$value->getTelephone()."</p>";
    $contenu2 .="        <p class=card-text>Adresse : ".$value->getAdresse()." , ".$value->getVille()."</p>";
    $contenu2 .="        <p class=card-text>Code postal : ".$value->getCodePostal()."</p>";
    $contenu2 .="        <p class=card-text>Assurance maladie : ".$value->getAssuranceMaladie()."</p>";
    $contenu2 .="        <p class=card-text>Pays naissance : ".$value->getPaysNaissance()."</p>";
    $contenu2 .="        <p class=card-text>Date Naissance : ".$value->getDateNaissance()."</p>";
    $contenu2 .="        <p class=card-text>Sexe : ".$sexe->getGenre()."</p>";
    $contenu2 .="        <p class=card-text>Groupe sanguin : ".$sang->getGroupeSanguin()."</p>";
    $contenu2 .="        <h4 class=card-text><u>Diagnostic</u></h4>";
    $contenu2 .="        <p class=card-text>Description : ".$value->getDescription()."</p>";
    $resultPrescription = $prescriptionManager->getPrescription($value->getIdPatient());
    if($resultPrescription != null){
        $contenu2 .="        <h4 class=card-text><u>Prescription</u></h4>";
        foreach($resultPrescription as $key => $value){
            $employer = $employerManager->getEmployer($value->getIdEmployer());
            $hopital = $hopitalManager->getHopital($value->getIdHopital());
            $contenu2 .="        <b class=card-text>".$hopital->getNom()."</b><br><br>";
            $contenu2 .="        <i class=card-text>Employer : ".$employer->getNom()." ".$employer->getPrenom()."</i>";
            $contenu2 .="        <p class=card-text>".$value->getDate()."</p>";
            $contenu2 .="        <p class=card-text>".$value->getDescription()."</p>";
        }
    }
    $contenu2 .="        <input type='hidden' name='idPatient' value=".$value->getIdPatient().">";
    $contenu2 .="        <input type='submit' name='facture' value='Facture'>";
    $contenu2 .="        <input type='submit' name='transferer' value='Transfèrer'>";
    $contenu2 .="        <input type='submit' name='supprimer' value='Supprimer'><br>";
    $contenu2 .="    </div></div></form>";
    echo $contenu2;
}
if(isset($_POST["supprimer"])){
    $array = array("idPatient" => $_POST["idPatient"]);
    $idPatient = new patient($array);
    $patientManager->supprimer($idPatient);
    ?>
    <script>window.location.replace("dashboard/projet/mvc/affichePatient");</script><?php
}
}
?>