<?php
    
if (isset($_POST["connection"])){
    if (isset($_POST["pseudo"]) && isset($_POST["motDePasse"])){

        if($_POST["poste"] == "patient"){
            $array = array("pseudo" => $_POST['pseudo'],"motDePasse" => $_POST['motDePasse']);
            $patient = new patient($array);
            $patientManager = new patientManager(connexion("bdd_hms"));
            $results = $patientManager->getPatientLog($patient);
        }
        if($_POST["poste"] == "employer"){
            $array = array("pseudo" => $_POST['pseudo'],"motDePasse" => $_POST['motDePasse']);
            $employer = new employer($array);
            $employerManager = new employerManager(connexion("bdd_hms"));
            $results = $employerManager->getEmployerLog($employer);
            $_SESSION['idPoste'] = $results->getIdPoste();
            $_SESSION['id'] = $results->getIdEmployer();
        }

        if ($results != false) 
        {
            $_SESSION['pseudo'] = $_POST['pseudo'];
            $_SESSION['motDePasse'] = $_POST['motDePasse'];

            if($_POST["poste"] == "patient"){
                header("Location:patient");
            }
            elseif($_POST["poste"] == "employer"){
                header("Location:profil");
            }
        }
        else{
            echo '<script>alert("Veuillez vous inscrire!")</script>';
        }
    }
}
?>

<div class="topnav">
    <a class="active" style="float:right" href="dashboard/projet/mvc/connection">Se connecter</a>
    <a class="active" style="float:right" href="dashboard/projet/mvc/inscription">Inscription</a>
    <a class="active" style="float:right" href="dashboard/projet/mvc/accueil">Accueil</a>
</div>

<center>
<div>
    <br><br><br><br>
    <form method="post">
        <h1 style=color:black>Connection</h1>
        <select name="poste" style="width:178px;">
        <option value="patient" selected>Patient</option>
        <option value="employer">Employer</option>
        </select><br><br>
        <input type="text" name="pseudo" placeholder="Pseudo" id="pseudo" minlength="6" maxlength='30' required><br><br>
        <input type="password" name="motDePasse" placeholder="Mot de passe" id="motDePasse" minlength="6" maxlength='30' required><br><br>
        <input type="submit" name="connection" value="Connecter"><br><br>
    </form>
</div>
<br><br><br><br><br><br><br><br><br><br><br><br>
</center>