<style>
.card { float:left;box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);  transition: 0.3s;  width: 300px;  border-radius: 5px;  padding: 1.6%; margin:1%;}
.card:hover {  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);}
img {  border-radius: 5px 5px 0 0;  width: 400px;  height: 400px;}
.container {  width:100%;}
#right {  float:right;  border: 3px solid lightskyblue;}
</style>
<?php
include_once("./fonction.php");

$hopitalManager = new hopitalManager(connexion("bdd_hms"));
$result = $hopitalManager->getAllHopital();

$departementManager = new departementManager(connexion("bdd_hms"));
$resultAllDepartement = $departementManager->getAllDepartement();

if(isset($_POST['modifier'])){
    $array = array("adresse" => trim($_POST['adresse']),
                    "nom" => trim($_POST["nom"]),
                    "ville" => trim($_POST["Ville"]),
                    "codePostal" => trim($_POST['codePostal']),
                    "telephone" => trim($_POST['telephone']),
                    "idHopital" => $_POST['idHopital']);

    $hopital = new hopital($array);
    $hopitalManager = new hopitalManager(connexion("bdd_hms"));
    try{
    $hopitalManager->update($hopital);?>
    <script>window.location.replace("dashboard/projet/mvc/hopital");</script><?php
    }
    catch(Exception $e){
        echo '<script>alert("Modification échoué!")</script>';
    }
}
if(isset($_POST['supprimer'])){
    $departementManager = new departementManager(connexion("bdd_hms"));
    $array = array("idDepartement" => $_POST["departement"]);
    $departement = new departement($array);
    $departementManager->supprimer($departement);
    ?>
    <script>window.location.replace("dashboard/projet/mvc/hopital");</script><?php
}
if(isset($_POST['ajouter'])){
    $array = array( "departement" => trim($_POST['dep']));

    $departement = new departement($array);
    $departementManager = new departementManager(connexion("bdd_hms"));
    try{
    $departementManager->inserer($departement);
    ?>
        <script>window.location.replace("dashboard/projet/mvc/hopital");</script><?php
    }
    catch(Exception $e){
        echo '<script>alert("Ajout échoué!")</script>';
    }
}
?>
<br>
<div>
    <?php
    $contenu1 ="<form method='post'>&nbsp;&nbsp;&nbsp;&nbsp;Département : <select name=departement style=width:176px;>";
    foreach($resultAllDepartement as $key => $value){
        $contenu1 .="<option value=".$value->getIdDepartement().">".$value->getDepartement()."</option>";
    }
    $contenu1 .="</select>";
    $contenu1 .="<input type='submit' style=width:100px name='supprimer' value='Retirer'></form>&nbsp;&nbsp;";
    $contenu1 .="<form method='post'>&nbsp;&nbsp;&nbsp;&nbsp;Nouveau :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=text name=dep maxlength=30 placeholder=Departement required>";
    $contenu1 .="<input type='submit' style=width:100px name='ajouter' value='Ajouter'></form>";
    echo $contenu1;?>
</div>
<center>
<?php
foreach($result as $key => $value){
    $contenu = "";
    $contenu .="<form method='post'><div class=card>";
    $contenu .="<img src=".$value->getPhoto()." alt=Avatar style=width:100%>";
    $contenu .="<div class=container>";
    $contenu .="<h3 class=card-title>".$value->getNom()."</h3>";
    $contenu .="<p class=card-text>Nom :  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=text name=nom  value='".$value->getNom()."' required></p>";
    $contenu .="<p class=card-text>Adresse : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=text name=adresse maxlength=100 value='".$value->getAdresse()."' required></p>";
    $contenu .="<p class=card-text>Ville : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=text name=Ville maxlength=50 value='".$value->getVille()."' required></p>";
    $contenu .="<p class=card-text>Code Postal : <input type=text name=codePostal pattern=[A-Z]{1}[0-9]{1}[A-Z]{1}[0-9]{1}[A-Z]{1}[0-9]{1} value='".$value->getCodePostal()."' required></p>";
    $contenu .="<p class=card-text>Telephone :&nbsp;&nbsp;&nbsp; <input type=text name=telephone pattern=[0-9]{10} value='".$value->getTelephone()."' required></p><br>";
    $contenu .="<input type='hidden' name='idHopital' value=".$value->getIdHopital().">";
    $contenu .="<input type='submit' style=width:100px name='modifier' value='Modifier'>";
    $contenu .="</div>";
    $contenu .="</div></form>";
    echo $contenu;
}
?>
</center>