<?php
$sexeManager = new sexeManager(connexion("bdd_hms"));
$resultSexe = $sexeManager->getAllSexe();

$sangManager = new groupeSanguinManager(connexion("bdd_hms"));
$resultSang = $sangManager->getAllSang();

if(isset($_POST['inscrire'])){
    $erreur = inscription();
    if($erreur == 1){
        $msg = "Login deja utiliser ou l age n est pas un nombre";
        messageErreur($msg);
    }else{
        $msg = "Vous etes inscrit!";
        messageErreur($msg);
    }
}
?>

<div class="topnav">
    <a class="active" style="float:right" href="dashboard/projet/mvc/connection">Se connecter</a>
    <a class="active" style="float:right" href="dashboard/projet/mvc/inscription">Inscription</a>
    <a class="active" style="float:right" href="dashboard/projet/mvc/accueil">Accueil</a>
</div>

<center>
<div>
    <form method="post">
        <h1 style=color:black>Inscription</h1>
        <table>
            <tr>
                <td>Prenom  </td>
                <td><input type="text" name="prenom" required></td>
            </tr>
            <tr>
                <td>Nom  </td>
                <td><input type="text" name="nom"  required></td>
            </tr>
            <tr>
                <td>Telephone  </td>
                <td><input type="text" name="telephone" required></td>
            </tr>
            <tr>
                <td>Adresse  </td>
                <td><input type="text" name="adresse" required></td>
            </tr>
            <tr>
                <td>Ville  </td>
                <td><input type="text" name="ville" required></td>
            </tr>
            <tr>
                <td>Code Postal  </td>
                <td><input type="text" name="codePostal" required></td>
            </tr>
            <tr>
                <td>Sexe  </td>
                <td>
                <?php
                $contenu ="<select name=sexe style=width:100%;>";
                foreach($resultSexe as $key => $value){
                    $contenu .="<option value=".$value->getIdSexe().">".$value->getGenre()."</option>";
                }
                $contenu .="</select>";
                echo $contenu;
                ?>
            </tr>
            <tr>
                <td>Groupe Sanguin  </td>
                <td>
                <?php
                $contenu ="<select name=grpSang style=width:100%;>";
                foreach($resultSang as $key => $value){
                    $contenu .="<option value=".$value->getIdGroupeSanguin().">".$value->getGroupeSanguin()."</option>";
                }
                $contenu .="</select>";
                echo $contenu;
                ?>
                </td>
            </tr>
            <tr>
                <td>Assurance Maladie  </td>
                <td><input type="text" name="assuranceMaladie" required></td>
            </tr>
            <tr>
                <td>Pays de naissance  </td>
                <td><input type="text" name="paysNaissance" required></td>
            </tr>
            <tr>
                <td>Date de naissance  </td>
                <td><input type="date" name="dateNaissance" style="width:97%;" required></td>
            </tr>
            <tr>
                <td>Pseudo  </td>
                <td><input type="text" name="pseudo" required></td>
            </tr>
            <tr>
                <td>Mot de passe  </td>
                <td><input type="password" name="motDePasse" required></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" name="inscrire" value="Inscrire"></td>
            </tr>
        <table>
    </form>
</div>

</center>
<br><br><br>