<!DOCTYPE html>
<html lang="en">
<head>
	<base href="/localhost" />
	<meta charset="UTF-8" />
	<title><?= $title ?></title>
	<meta name="description" content="<?= $description ?>" />
	<link href= "dashboard/projet/mvc/Style.css" rel="stylesheet" type="text/css">
</head> 

<body>
<header>
	<img src="https://www.mutuelledelacorse.com/wp-content/uploads/2020/03/iStock-885314598-scaled.jpg" style="height:350px;width:100%">
</header>

<article>
	<?php $this->controller->renderView(); // renders the current view into the template ?>
</article>
<br><br><br>
<footer style="position: fixed;   left: 0;   bottom: 0;   width: 100%;   text-align: center;">
		<p>Développer par Yanick Clermont.</p>
</footer>
</body>
</html>
