<style>
.card { float:left;box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);  transition: 0.3s;  width: 300px;  border-radius: 5px;  padding: 20px; margin:10 auto;}
.card:hover {  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);}
img {  border-radius: 5px 5px 0 0;  width: 300px;  height: 400px;}
.container {  width:100%;}
#right {  float:right;  border: 3px solid lightskyblue;}

.center1 {  margin: auto;  width: 60%;  border: 3px solid lightskyblue;  padding: 10px;}
.card1 {  float: left; background: rgba(0, 128, 0, 0.3);box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);  transition: 0.3s;  width: 300px;  border-radius: 5px;  padding: 10px;margin: 10px;}
.card1:hover {  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);}
.container1 {  width:100%;}
</style>
<?php
include_once("./fonction.php");
$mode = 0;
$employerManager = new employerManager(connexion("bdd_hms"));
$result = $employerManager->getMedecin(1);

if(isset($_POST["shedule"])){
    $mode = 1;
    $sheduleManager = new sheduleManager(connexion("bdd_hms"));
    $resultShedule = $sheduleManager->getSheduleDispo($_POST["idEmployer"]);

    $rendezvousManager = new rendezvousManager(connexion("bdd_hms"));
    $resultRendezvous = $rendezvousManager->getPatientRendezvous($_SESSION["id"]);

    foreach($resultShedule as $key => $value){
        $contenu2  = "<div class=card1>";
        $contenu2 .="<form method='post'><div class=container1>";
        $contenu2 .="        <h3 class=card-title>".$value->getJour()."</h3><hr>";
        $contenu2 .="        <p class=card-text style=background-color: green>Frais : ".$value->getFrais()."</p>";
        $contenu2 .="        <p class=card-text>Shedule : ".$value->getShedule()."</p>";
        $contenu2 .="        <p class=card-text>Place(s) restante(s) : ".$value->getCmpPatient()."</p>";
        $contenu2 .="        <input type='hidden' name='idEmployer' value=".$value->getNoEmployer().">";
        $contenu2 .="        <input type='hidden' name='id' value=".$value->getIdShedule().">";
        $contenu2 .="        <input type='hidden' name='defaultCmp' value=".$value->getCmpPatient().">";
        $contenu2 .="<input type='hidden' name='idHopital' value=".$_POST["idHopital"].">";
        $contenu2 .="        <input type='submit' name='reserver' id='reserver' value='Réserver'><br>";
        $contenu2 .="    </div></div></form>";
        echo $contenu2;

        foreach($resultRendezvous as $key => $value1){
            if($value1->getIdShedule() == $value->getIdShedule()){
                ;?><script>document.getElementById("reserver").disabled = true; </script><?php
            }
        }

    }
}

if(isset($_POST["reserver"])){
    $array = array("idShedule" => $_POST['id'],"idPatient" => $_SESSION["id"],"idEmployer" => $_POST["idEmployer"],"idHopital"=> $_POST["idHopital"]);
    $rendezvous = new rendezvous($array);
    $rendezvousManager = new rendezvousManager(connexion("bdd_hms"));
    $rendezvousManager->insertion($rendezvous);

    $defaultCmp = $_POST["defaultCmp"] - 1;
    $arrayDefaultShedule = array("idShedule" => $_POST['id'],"cmpPatient" => $defaultCmp);
    $sheduleDefault = new shedule($arrayDefaultShedule);
    $sheduleManager = new sheduleManager(connexion("bdd_hms"));
    $sheduleManager->updateCmp($sheduleDefault);

    
    if($defaultCmp == 0){
        $arrayDefaultShedule = array("idShedule" => $_POST['id'],"disponibilite" => 0);
        $sheduleDefault = new shedule($arrayDefaultShedule);
        $sheduleManager->updateDisponibilite($sheduleDefault);
    }
    echo "<center><p style=color:green;>Rendez Vous confirmé!</p></center>";
}

if($mode == 0){
    foreach($result as $key => $value){
        $posteManager = new posteManager(connexion("bdd_hms"));
        $resultPoste = $posteManager->getPoste($value->getIdPoste());

        $hopitalManager = new hopitalManager(connexion("bdd_hms"));
        $resultHopital = $hopitalManager->getHopital($value->getIdHopital());

        $departementManager = new departementManager(connexion("bdd_hms"));
        $resultDepartement = $departementManager->getDepartement($value->getIdDepartement());

        $contenu2  ="<div class=card>";
        $contenu2 .="<form method='post'><div class=container>";
        $contenu2 .="<img src=".$value->getPhoto()." alt=Avatar style=width:100%>";
        $contenu2 .="<h3 class=card-title>".$value->getPrenom()." ".$value->getNom()."</h3><hr>";
        $contenu2 .="<p>".$value->getCourriel()."</p>";
        $contenu2 .="<p>".$resultPoste->getPoste()."</p>";
        $contenu2 .="<p>Hopital ".$resultHopital->getNom()."</p>";
        $contenu2 .="<p>Département : ".$resultDepartement->getDepartement()."</p>";
        $contenu2 .="<p>Employer No : ".$value->getIdEmployer()."</p>";
        $contenu2 .="<input type='hidden' name='idEmployer' value=".$value->getIdEmployer().">";
        $contenu2 .="<input type='hidden' name='idHopital' value=".$value->getIdHopital().">";

        $sheduleManager = new sheduleManager(connexion("bdd_hms"));
        $resultShedule = $sheduleManager->getSheduleDispo($value->getIdEmployer());

        if($resultShedule != null){
            $contenu2 .="<p>Disponible : <b style=color:green;> Oui </b></p>";
            $contenu2 .="<center><input type='submit' style=width:100px name='shedule' value='Shedule'></center>";
        }else{
            $contenu2 .="<p>Disponible : <b style=color:red;> Non </b></p>";
            $contenu2 .="<center><input type='submit' disabled style=width:100px name='shedule' value='Shedule'></center>";
        }
        $contenu2 .="</div></div></form>";
        echo $contenu2;
    }
}